language: java
jdk:
- oraclejdk8
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAI7SK5573GGSPOFNA
  secret_access_key:
    secure: 19Tqu1s/muyxsIZk+T82N7RPoUF2Lwir/OvYIkSmAYzZpl+xHk4gzHnS05taKPFezjnNreGoSKFK/pDWfFjL2FRQbZY9oNN92U2YcSMVs9lbQvCTiasoFdB1a3C2zQ9BA7VVFOI7XQrNh2I4cwKelRUckHvj9IhLXDTNrSUi0pfeSJTA4PR+OT474wyAc7nbdOui79XgezH/9FBWy5pa19m1WaC4OZus1mr8zrPfS7m3NrqU96O4Up4kIxyU2ddCNXhC+nmCa4OQSAWLg/jFRQAPLX+N4vdp9Wii6rfEovQIVAbXLcOvPoxAW0BpxBkmHl32ZmycGYJOTyLLW1W6jTJ+l92sT+23j/pdtO4PGVJqEARrKsVVjEXNHwhe92ksnD+gvRkMcgoRvR0DYhFS/4mTnKoq46XXaqBOH2R/4uN65MRVdVBjFkcwK/gU0555ZEgVE2UgJXRmmHHYQUQOSvjAGHWeqC2KrPmz+Roq29/nMYqmjkviQE2adO/2dqSO64EsShM3kl/GJdLaVw1ONcB0o4FO+cQKJlH1327MfEv+1PsdnP0HEJQjOyzMprKlwUiAbun7BwC0E8rqEiS79L6mgaxxxOD9T06iE5G9uABE/v8GnQJ0r4x7d3tkTrht/ZcNBgVDlCCNQ0Q8oMZBLItIyWdO8jtn64FgL29YKMg=
  region: us-east-2
  app: Tom-Talk
  env: Tom-Talk-env
  on:
    repo: ThomGeG/Tom-Talk
  skip_cleanup: true
